const pages=["Analyze","Dashboard","History","Backtest","Scanner","Watchlist","Alerts","Analytics","Reports","Settings","Account","Logout"];
const nav=document.getElementById("nav"),content=document.getElementById("content"),title=document.getElementById("title");
pages.forEach(p=>{let b=document.createElement("button");b.textContent=p;b.onclick=()=>load(p);nav.appendChild(b)});
function card(html){return `<div class="card">${html}</div>`}
async function api(url,opt){let r=await fetch(url,opt);let j=await r.json();if(!r.ok)throw Error(j.detail||"Request failed");return j.data}
async function load(p){title.textContent=p;document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.textContent===p));
if(p==="Analyze")return analyzePage(); if(p==="Dashboard")return simple("/api/dashboard",d=>`<div class="grid"><div class="card">Analyses<div class="metric">${d.analyses}</div></div><div class="card">LONG<div class="metric">${d.long}</div></div><div class="card">SHORT<div class="metric">${d.short}</div></div><div class="card">NEUTRAL<div class="metric">${d.neutral}</div></div></div>`);
if(p==="History")return tablePage("/api/history",["symbol","timeframe","signal","score","entry","sl","tp1"]);
if(p==="Backtest")return backtestPage(); if(p==="Scanner")return scannerPage(); if(p==="Watchlist")return simple("/api/watchlist",d=>JSON.stringify(d,null,2)); if(p==="Alerts")return simple("/api/alerts",d=>JSON.stringify(d,null,2));
if(p==="Analytics")return simple("/api/analytics",d=>JSON.stringify(d,null,2)); if(p==="Reports")return simple("/api/reports",d=>JSON.stringify(d,null,2));
if(p==="Settings")return simple("/api/settings",d=>JSON.stringify(d,null,2)); if(p==="Account")return simple("/api/account",d=>JSON.stringify(d,null,2)); content.innerHTML=card("خروج از حساب در این نسخه صرفاً رابط کاربری است.");}
function analyzePage(){content.innerHTML=card(`<h3>Market Analysis</h3><div class="row"><input id="sym" value="BTCUSDT"><select id="tf"><option>5m</option><option selected>15m</option><option>30m</option><option>1h</option><option>4h</option><option>1d</option></select><button class="action" onclick="doAnalyze()">Analyze</button></div><div id="result">—</div>`)}
async function doAnalyze(){let r=document.getElementById("result");r.textContent="در حال تحلیل...";try{let d=await api("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:document.getElementById("sym").value,timeframe:document.getElementById("tf").value})});let l=d.levels;r.innerHTML=`<h2>${d.signal} — ${d.confluence_score}</h2><p>Entry ${l.entry.toFixed(4)} | SL ${l.sl.toFixed(4)} | TP1 ${l.tp1.toFixed(4)} | TP2 ${l.tp2.toFixed(4)} | TP3 ${l.tp3.toFixed(4)}</p><p>RSI: ${d.details.indicators.rsi.toFixed(2)} | MACD: ${d.details.states.macd>0?"Bullish":"Bearish"} | Ichimoku: ${d.details.indicators.ichimoku} | PSAR: ${d.details.states.psar>0?"Bullish":"Bearish"}</p>`}catch(e){r.textContent=e.message}}
async function simple(url,fmt){try{content.innerHTML=card(`<pre>${fmt(await api(url))}</pre>`)}catch(e){content.innerHTML=card(e.message)}}
async function tablePage(url,cols){try{let d=await api(url);let h="<table><tr>"+cols.map(x=>`<th>${x}</th>`).join("")+"</tr>"+d.map(r=>"<tr>"+cols.map(x=>`<td>${r[x]??""}</td>`).join("")+"</tr>").join("")+"</table>";content.innerHTML=card(h)}catch(e){content.innerHTML=card(e.message)}}
function backtestPage(){content.innerHTML=card(`<h3>Backtest</h3><div class="row"><input id="bs" value="BTCUSDT"><select id="bt"><option>15m</option><option>1h</option><option>4h</option></select><button class="action" onclick="bt()">Run Backtest</button></div><div id="bo"></div>`)}
async function bt(){try{let d=await api("/api/backtest/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:document.getElementById("bs").value,timeframe:document.getElementById("bt").value,initial_balance:10000})});document.getElementById("bo").innerHTML=JSON.stringify(d,null,2)}catch(e){document.getElementById("bo").textContent=e.message}}
async function scannerPage(){content.innerHTML=card(`<h3>Scanner</h3><select id="st"><option>15m</option><option>1h</option><option>4h</option></select><button class="action" onclick="scan()">Scan</button><div id="so"></div>`)}
async function scan(){try{let d=await api("/api/scanner/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:"BTCUSDT",timeframe:document.getElementById("st").value})});document.getElementById("so").innerHTML=JSON.stringify(d.results,null,2)}catch(e){document.getElementById("so").textContent=e.message}}
load("Analyze");
